name: mironline
description: "Pocket version for make it real and mironline language learning resources!"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  kg_charts: ^0.0.5
  rive: ^0.13.20
  shared_preferences: ^2.4.0
  google_sign_in: ^6.2.2
  google_fonts: ^6.2.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  dio: ^5.3.3
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.2.0
  crypto: ^3.0.6
  webview_flutter: ^4.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/logo.png"
  remove_alpha_ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/images/
    - assets/images/google_logo.png
    - assets/images/egp-levels/
    - assets/animations/
    - assets/svgs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
