name: mironline
description: "Pocket version for make it real and mironline language learning resources!"
publish_to: 'none' 

version: 1.0.6+18

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  kg_charts: ^0.0.5
  rive: ^0.13.20
  shared_preferences: ^2.4.0
  google_sign_in: ^7.1.1
  google_fonts: ^6.2.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  intl: ^0.20.2
  flutter_secure_storage: ^9.0.0
  dio: ^5.3.3
  flutter_riverpod: ^3.0.0-dev.17
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^3.0.0-dev.17
  crypto: ^3.0.6
  webview_flutter: ^4.10.0
  flutter_dotenv: ^6.0.0
  http: ^1.5.0
  app_set_id: ^1.3.0
  webview_flutter_android: ^4.10.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  freezed: ^3.2.0
  json_serializable: ^6.9.4
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0-dev.17

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo.png
    - assets/images/
    - assets/images/google_logo.png
    - assets/images/egp-levels/
    - assets/animations/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
